parameters:
#    sms_api_common_layout.example.class: SMSApi\Bundle\CommonLayoutBundle\Example

services:
#    sms_api_common_layout.example:
#        class: %sms_api_common_layout.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
